---
title: 'Helicopter Seeds ($\emptyset$)'
format: html
code-fold: True
---

The seeds from lime, maple, and elm trees have curved wings to let them stay in the air longer. The wind can pick up these seeds and may carry them to suitable groud. These seeds twirl and spin around. They will then drop and sprount a new tree. Some people call these seeds **helicopter seeds** because they look like and can spin like a propeller.

Here you will learn how to make your own paper spinner with two different designs. Precut origami paper and paper-clips are available at the Dundee Botanic Garden reception during Maths Week Scotland (September 2026).

## Design 1:

1. Fasten the two ends together with a paper clip.

2. Find a seed spinner in the garden. Drop both spinners from the same height and compare how they spind. Does your spinner work as well as nature's?


## Design 2:

1. Fold wing A and wing B down in opposite directions.

2. Fold up the flap E at the bottom of the origami.

3. Then fold flap C and flap D inwards, onto the centre area.

4. Place a paper clip on the bottom of the helicopter (where E, C and D overlap).

5. Throw your seed helicopter high and let it spin down!

6. Observe how the actual seed and your helicopter seed fly. Is it the same, or different?
